<a href="https://colab.research.google.com/github/MilanShri/ajay-shirvas/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Theoretical** **Questions**:

Ques 1) Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans) Numpy is a fundamental liberary in python for scientific computing deal with multidimentional array and perform various mathematical operations effeciently.

advantage - Numpy is ideal for halding large amount of data (homogenous data), offering significant improvement in speed and memory management, making it a powerful tool for scientific compution and data processing on the CPU.

Ques 2)  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans) In numpy library, both np.mean() and np.average() can be used to calculate arithmetic mean. The differenece comes when we have to perform average on weighted array. np.average() gives us flexibilty to work with the weighted arrays too. If we pass the weight of the array to the function, it can perform weighted average at very ease. That is not the case for the np.mean(). It can only be perfomred on non-weighted arrays.


Ques 3)  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans) We can reverse the array through the slicing or by using np.flipud() and np.filplr() numpy methods.

In [ ]:
import numpy as np  # 1 dim array reverse

arr1 = np.array([1,2,3,4,5])
reverse_arr1 = arr1[::-1]
print("\n the original array is :", arr1)
print("\n the reverse array is :",  reverse_arr1)


 the original array is : [1 2 3 4 5]

 the reverse array is : [5 4 3 2 1]


In [ ]:
import numpy as np # 2 dim array

arr2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("\n the original array is :")
print(arr2)
print("\n the reverse 2 d array up and down is :")
reverse_arr2 = np.flipud(arr2)
print(reverse_arr2)


 the original array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 the reverse 2 d array up and down is :
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Ques 4)  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans) In numpy, the data type of the elements in an array is essetial for efficient memory management and performance optimization.

In [ ]:
import numpy as np
arr = np.array([1,4,5,2,3,6])  # this is implicite data type where python knows the data type by default.
print("\n the data type of this give array is :", arr.dtype)



arr2 = np.arange(10, dtype = np.float16)  # this is explicite data type when we intentially change the data type.

print(arr2)
print(arr2.dtype)



 the data type of this give array is : int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float16


Ques 5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans) n-dimensional array are the core data structure for handling numerical data efficently. an ndarray is a high-performance container of large data set.

features are --

1) homogenous in nature (eg. all int, all float)

2) multidimensional

3) effective memory management


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[10 20 30 40]
(4,)
1


In [ ]:
import numpy as np
arr2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
(2, 2, 2)
3


Ques 6)  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

Ans) Memory efficiency - Numpy array is that they store sata in continous block of memory, meaning that all the elements are stored next to each otehr. this allow for more efficient access and manipulation of data compare to python list.

Python list s can hold elements of differnt data types. which makes them less memory efficient in nature for large dataset. numpy arrays are homogenous in nature.

Due to continkus memory layout, accessing elements in numpy arrar is faster than python list.

Numpy mainly deals with array so it is more flexible and faster than list.



Ques 7)  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans) vstake - vertically stack array and hstake -- horizontal stack array.

numpy.hstack() function is used to stack the sequence of input array horizontally to make a single array

numpy.vstack() function is used to stack the sequence of input array vertically to make a single array

the array must have the same shape.


In [ ]:
a = np.array([11,12,13])
b = np.array([14,15,16])
c = np.hstack((a,b))
print(c)

[11 12 13 14 15 16]


Ques 8)  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans)

In [ ]:
# fliplr() function is used to flip the array left to right
# flipud() function is used to flip the array up to down

import numpy as np # 2 dim array

arr2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("\n the original array is :")
print(arr2)
print("\n the reverse 2 d array up and down is :")
reverse_arr2 = np.flipud(arr2)
print(reverse_arr2)


 the original array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 the reverse 2 d array up and down is :
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Ques 9) . Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans) Numpy array are an essential part for scientfic calculations, so it become necessary to manipulate and analyse specific parts of the data .

the split(), hsplit(), vsplit(), and dsplit() functions are important tool for dividing array along various axes and dimension.

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
array1 = np.array_split(arr, 3)
print(array1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np
array = np.arange(6)
result = np.split(array, 2)
print(array)
print(result)

[0 1 2 3 4 5]
[array([0, 1, 2]), array([3, 4, 5])]


Ques 10)  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans) Broadcasting in numpy is a powerfull feature that allows to work with array of different shape when performance arithematic operations. it does this by broadcasting.

ex - you have score of 5 students i.e

score = [20,30,40,50,60]

and want to add 5 bonus to each score then

bonus = [5]

result will be = [25,35,45,55,60]


In [ ]:
score = np.arange(5)
print("\n the score of the students are :", score)
bonus = [5]
result = score+bonus
print("\n the final score of the students after adding bonus are :", result)


 the score of the students are : [0 1 2 3 4]

 the final score of the students after adding bonus are : [5 6 7 8 9]


**Practical Questions:**

Ques 1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
from numpy import random
x = random.randint(100, size = (3,3))
print(x)


[[66 98 34]
 [64 53 79]
 [70 45 63]]


In [ ]:
import numpy as np
from numpy import random
x = random.randint(1, 101, size = (3,3))
print(x)
print("\n reshape Array")
# y = x.reshape()
y = x.T
print(y)



[[59 58 41]
 [76 62 98]
 [61 78 67]]

 reshape Array
[[59 76 61]
 [58 62 78]
 [41 98 67]]


Ques 2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np
from numpy import random
arr = random.randint(20, size = 10)
print(arr)
print("\n the reshape array is 2*5 :")
new_arr = arr.reshape(2,5)
print(new_arr)

print("\n the reshape array is 5*2 :")
new_arr1 = arr.reshape(5,2)
print(new_arr1)

[ 0 14 16 15  0  0  7  0  7 19]

 the reshape array is 2*5 :
[[ 0 14 16 15  0]
 [ 0  7  0  7 19]]

 the reshape array is 5*2 :
[[ 0 14]
 [16 15]
 [ 0  0]
 [ 7  0]
 [ 7 19]]


Ques 3) Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [ ]:
import numpy as np
from numpy import random
arr = random.random(size = (4,4))
print(arr)

print("\n print array with 0 around it")

arr_with_zeros = np.pad(arr, pad_width = 1, mode = "constant", constant_values = 0)
print(arr_with_zeros)

print("\n the dim of this array :", arr_with_zeros.ndim)
print("\n the shape is :", arr_with_zeros.shape)

[[0.2847411  0.52386044 0.82507117 0.10343444]
 [0.70942168 0.9377681  0.22529691 0.51059317]
 [0.45359343 0.38963929 0.4336274  0.75328069]
 [0.09804406 0.17896975 0.94697263 0.99270694]]

 print array with 0 around it
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.2847411  0.52386044 0.82507117 0.10343444 0.        ]
 [0.         0.70942168 0.9377681  0.22529691 0.51059317 0.        ]
 [0.         0.45359343 0.38963929 0.4336274  0.75328069 0.        ]
 [0.         0.09804406 0.17896975 0.94697263 0.99270694 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]

 the dim of this array : 2

 the shape is : (6, 6)


Ques 4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np
from numpy import random
arr3 = np.arange(10,61,5)
arr3

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Ques 5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np
arr = np.array(('python', 'numpy', 'pandas'))
upper_arr = np.char.upper(arr)
lower_arr = np.char.lower(arr)
title_arr = np.char.title(arr)
print(title_arr)
print(lower_arr)
print(upper_arr)


['Python' 'Numpy' 'Pandas']
['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']


Ques 6)  Generate a NumPy array of words. Insert a space between each character of every word in the array

In [27]:
import numpy as np
arr = np.array(('python', 'numpy', 'pandas'))
print(arr)
#######################################################3 incorrect
space_arr = np.char.add(" " , np.char.add(arr,","))
print(space_arr)

['python' 'numpy' 'pandas']
[' python,' ' numpy,' ' pandas,']


Ques 7)  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
c+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c-10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [ ]:
c*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
c/5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

Ques 9) Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array

In [ ]:
import numpy as np
from numpy import random
new_arr = random.randint(0, 1000, size = 100)
print(new_arr)



[434 777 302 473  50 185  76  71 650 766 596 111 626 614 485 139 633 999
 173 486 280 365 788 451 990 325 251 183 122  37 554 173 496 817 500 179
 458 806 209 411 183 752 203 530 121 295 656 543 198 118  74 447 200 772
 621 205 679 939 853 597 382 644 813 442 108 153 260 201 332 897 116 350
 997 882 592 833 393 930 301 394 269 245 648 310 886 794 513 202 187 629
 506  26 269 986 656 310 799 185 734 447]


In [8]:
import numpy as np
from numpy import random

# Generate an array with 100 random integers between 0 and 1000
new_arr = random.randint(0, 1000, size=100)
print("Generated Array: ", new_arr)

def is_prime(num):
    if num <= 1:
        return False  # Numbers less than or equal to 1 are not prime
    for i in range(2, int(num**0.5) + 1):  # Only check divisibility up to sqrt(num)
        if num % i == 0:
            return False  # num is divisible, so it's not prime
    return True  # num is prime

# Find prime numbers in the array
primes = [num for num in new_arr if is_prime(num)]
print("Prime Numbers: ", primes)


Generated Array:  [432 278 549 143 891 832  18 856 871 125 880 426 295 176 252 671  98 516
 167 699 700 266 416 624 507  29 674 968 357 201 581 846 289 297 298 751
 534 610 332 421 753 431 854 266 515 629 398 844 475 487 775 751 404 902
 829 430 311 875 558 170 778 845 115 171 268 244 689  96 814  54 238 387
 459  43 813 651 217 670 426 238 202 158 127 932 996 122 566 435 705 395
 468 145 455 651 622 883 405 796 895  70]
Prime Numbers:  [167, 29, 751, 421, 431, 487, 751, 829, 311, 43, 127, 883]


Ques 10)  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [24]:
import numpy as np
from numpy import random
new_arr = np.random.uniform(15, 35, size = (30)) # getting 30 days random temp through random.uniform function
print(new_arr)

# week_temp = new_arr.reshape(4,7)
week_temp = new_arr.reshape(6, -1) # consider 6 days = 1 week
print("\n first week temp can calculate like ")
week_temp = new_arr[:6]
print(week_temp)
print("\n the avg temp in week first is : ", week_temp.mean())

[34.44872175 17.52876841 33.94671777 26.68845867 15.12947683 22.85870729
 16.25011839 22.41876633 24.07612673 15.75630106 24.42428458 28.46309816
 28.24813675 24.14374883 34.78140477 32.2733895  34.9388917  17.92779314
 21.0543121  19.5891559  20.22356458 27.46333921 23.1806906  18.00538333
 17.07890486 19.64341398 15.73033288 17.259419   28.18265997 22.32543909]

 first week temp can calculate like 
[34.44872175 17.52876841 33.94671777 26.68845867 15.12947683 22.85870729]

 the avg temp in week first is :  25.100141785207413
